version: '3.9'

services: 
    

  webapp:
      container_name: LoginWebApp
      image: LoginWebApp
      build:
        context: .
        dockerfile: Dockerfile
      ports:
       - "5000:8080"
       - "3306:3306"
      volumes: ./logs:/usr/local/tomcat/logs