version: '3.9'

services: 
    

  webapp:
      container_name: loginwebapp
      image: loginwebapp
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
       - ./logs:/usr/local/tomcat/logs
      network_mode: "host"
      restart: on-failure